# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "jekyll", "~> 4.3.0"
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-include-cache"
gem "minima", "~> 2.5"
